extends RefCounted
# Original short adaptation text; not a reproduction of the screenplay.
const CHAPTERS = [
 {"title":"01 / WESTER DRUMLINS", "place":"house", "intro":"Sally Sparrow · 2007\nA derelict house. A camera. Something behind the wallpaper.", "steps":[["paper","Peel the loose wallpaper","A warning names Sally. Someone anticipated this visit."],["message","Photograph the exposed writing","The message is dated 1969 and signed by the Doctor."],["window","Examine the garden statue","An Angel faces the window. The camera records its position."]]},
 {"title":"02 / A RECORDED STRANGER", "place":"flat", "intro":"Later that night · Kathy’s flat", "steps":[["tv","Examine the television","A stranger appears in a DVD extra."],["kathy","Tell Kathy about the house","Kathy agrees to investigate with Sally in the morning."]]},
 {"title":"03 / THE LETTER", "place":"house", "intro":"The next morning · Kathy waits inside", "steps":[["window","Compare the statue with the photograph","Its position has changed."],["visitor","Answer the door","A visitor delivers a letter from his grandmother: Kathy."],["kathy","Return to Kathy","Kathy has vanished. The letter describes a life begun in 1920."],["key","Take the key from the statue’s hand","Sally pockets the key, then leaves."]]},
 {"title":"04 / YEARS IN A MORNING", "place":"garden", "intro":"A quiet pause · Read the letter and visit the grave", "steps":[["letter","Read Kathy’s letter","Kathy had a family. Her photographs show a full life."],["grave","Visit Kathy’s grave","Sally must tell Larry what happened to his sister."]]},
 {"title":"05 / SEVENTEEN DISCS", "place":"shop", "intro":"The DVD shop · Larry Nightingale", "steps":[["larry","Speak with Larry","Seventeen DVDs contain the same unexplained recording."],["tv","Inspect the DVD extra","The stranger’s pauses sound like half a conversation."],["list","Take Larry’s list","Sally takes the list to investigate further."]]},
 {"title":"06 / MISSING PERSONS", "place":"garage", "intro":"Police impound · Detective Billy Shipton", "steps":[["billy","Speak with Billy","Abandoned vehicles link several disappearances to the house."],["box","Inspect the police box","Its lock resembles the key from the Angel."],["exit","Leave the garage","Sally steps outside. Behind her, Billy encounters the Angels."],["box","Return to the police box","Billy and the box are gone. Sally’s phone rings."]]},
 {"title":"07 / THE LONG WAY ROUND", "place":"hospital", "intro":"Hospital · The same evening", "steps":[["billy","Sit with the elderly Billy","Sent to 1969, Billy grew old and worked in publishing."],["list","Compare the seventeen titles","Every disc belongs to Sally. The message is meant for her."],["window","Stay until the rain stops","Sally stays with Billy, then calls Larry."]]},
 {"title":"08 / THE CONVERSATION", "place":"house", "intro":"Wester Drumlins · Larry brings the player", "steps":[["tv","Play the recording","The Doctor is stranded in 1969. Observation freezes an Angel."],["larry","Record Sally’s responses","Larry writes the other half of the conversation."],["tv","Finish the message","The Doctor needs his TARDIS returned. The transcript ends."]]},
 {"title":"09 / KEEP WATCHING", "place":"house", "intro":"The doors are locked · Larry watches the nearest Angel", "danger":true, "steps":[["exit","Try the front door","Locked from outside."],["cellar","Find the cellar entrance","The cellar is the remaining route. Back away while watching."]]},
 {"title":"10 / THE CELLAR", "place":"cellar", "intro":"Four Angels · One police box", "danger":true, "steps":[["box","Reach the TARDIS and use the key","The key turns. Sally and Larry get inside."]]},
 {"title":"11 / ONE JOURNEY", "place":"tardis", "intro":"Inside the TARDIS · An authorised control disc", "steps":[["console","Insert Larry’s DVD","The TARDIS departs without its visitors."],["angels","Watch the Angels","The Angels face one another. They are permanently frozen."]]},
 {"title":"12 / THE LOOP", "place":"shop", "intro":"One year later · Sparrow & Nightingale", "steps":[["folder","Collect the evidence folder","Photographs, letters and the completed transcript."],["doctor","Give the folder to the Doctor","His encounter with the Angels is still ahead. Sally supplies the clues that saved her."]]}
]
